# fly.toml app configuration file generated for suburb-finder-backend on 2024-01-15T10:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "suburb-finder-backend"
primary_region = "syd"

[build]

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 